### ISSUE TITLE
井野奥义视角问题

### ISSUE THREAD

**Issue by wyf195075595** [real-re/nsv2-website#1]
井野奥义命中鸣人分身后，鸣人视角发生变化。变成井野的视角了 v2.1.1
![Screenshot_2022-05-15-11-06-56-809_re naruto game](https://user-images.githubusercontent.com/60338824/168455526-fb842d90-96a2-4c1b-8a69-24cb20dfc7b7.jpg)

**Comment by real-re** [comment]
已知bug，反馈bug转移到此处 https://support.qq.com/product/406951
